### ISSUE TITLE
What is FD 18 testing?

### ISSUE THREAD

**Issue by stevehjohn** [raddad772/jsmoo#25]
Hi.

Thanks for your awesome test files... I've been using them to implement a Z80 emulator.

My emulator passes everything I've implemented, but I can't get it to pass the test "FD 18".

Do you know what this is testing? I can't find that instruction combination documented anywhere...

Also, I seem to have a few unimplemented instructions that you test for. Are you privvy to some secret documentation? :D

Thanks,

Steve.

**Comment by raddad772** [comment]
Hey,

Thanks for using the tests! Remember if you find a mistake, it may be my fault; do look up the docs. I made these because my original Z80 core was trash, and I had really benefited from similar tests by someone else.

There's definitely some documentation for how X,Y and WZ work that isn't easy to find. The Undocumented Z80 Documented is a good start.

The source for the tests is available in this repository under misc/code_generation/z80_test_generator.js, and my Z80 core is available in the component/cpu/z80 sub-directory.

As to what FD 18 is testing...I guess this may or may not be a bug. Regular opcode 0x18 is defined as "JR_c_e", which is an unconditional relative jump. If you read Z80 Undocumented, you'll see (in reference to DD and FD):

```
In general, after a DD prefix the instruction is executed as if the DD
weren't there. There are some exceptions:

* Any access to HL is treated as an access to IX (except EX DE,HL and EXX
  and the ED prefixed instructions that use HL).
* Any access to (HL) is changed to (IX+d), where d is a signed displacement
  byte placed after the main opcode (except JP (HL), which isn't indirect
  anyways.
* Any access to H is treated as an access to IXh (the high byte of IX)
  Except if (IX+d) is accessed.
* Any access to L is treated as an access to IXl (the low byte of IX)
  Except if (IX+d) is accessed.
* A DD prefix before a CB selects a completely different instruction 
  set (see 1.5).
```

Anyway, none of those is fulfilled, so it's just treated as a regular 0x18. I know it doesn't show up in opcode tables like that, but it's the behavior the Z80 exhibits. The tests are generated by running through 0xFD00 to 0xFDFF and generating any possibly legal opcodes by running them on a Z80 core ported from Ares (and patched up in the meantime; I've submitted several upstream Z80 issues).

I also asked on the ZX Spectrum Emulator Discord, where there's a lot of people more knowledgeable about the Z80 than I am there, and this behavior was confirmed.

Thanks a bunch again!

Thanks again for using the tests! I'll post back here when I get a response
